- name: Request subnet list from API (list subnet)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/subnets"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: subnetlist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: subnetlist.status == 200
  changed_when: false

- debug:
    msg: "{{  subnetlist.json }}"
