- name: Lookup image_id
  include: lookup.yml

- name: Send request to API (show image)
  uri:
    url: "{{ AUTH_URL_IMS }}/v2/images/{{ image_id }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: imagedetail
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: imagedetail.status == 200
  changed_when: false
  when:
    - image_id is defined

- debug:
    msg: "{{ imagedetail.json }}"
