---
- hosts: localhost
  gather_facts: no
  vars:
    tenant_json: "vars/tenant.json"
    tenant_cf: "{{ lookup('file', tenant_json) | from_json }}"

    # Common defaults
    default_vars: "{{ tenant_cf['default'] }}"
    vm_vars: "{{ tenant_cf['vms'][ecs_name] | combine(default_vars, recursive=True) }}"
    evs_vars: "{{ tenant_cf['volumes'][evs_name] | combine(default_vars, recursive=True) }}"
    elb_vars: "{{ tenant_cf['elb'][elb_name] | combine(default_vars, recursive=True) }}"
    elb_listener_vars: "{{ tenant_cf['elblistener'][listener_name] | combine(default_vars, recursive=True) }}"
    dns_vars: "{{ tenant_cf['dnszones'][zone_name] | combine(default_vars, recursive=True) }}"
    rds_vars: "{{ tenant_cf['rds'][rds_name] | combine(default_vars, recursive=True) }}"
    
    # VM-specific variables
    image_name: "{{ vm_vars['image_name'] }}"
    availability_zone: "{{ vm_vars['availability_zone'] }}"
    vpc_name: "{{ vm_vars['vpc_name'] }}"
    vpc_net: "{{ vm_vars['vpc_net'] }}"
    subnet_name: "{{ vm_vars['subnet_name'] }}"
    subnet_net: "{{ vm_vars['subnet_net'] }}"
    subnet_gateway: "{{ vm_vars['subnet_gateway'] }}"
    secgroups: "{{ vm_vars['secgroups'] }}"
    ecs_ipaddress: "{{ vm_vars['ecs_ipaddress'] }}"
    public_ip_address: "{{ vm_vars['ecs_publicip'] }}"
    ptr_name: "{{ vm_vars['ecs_publicfqdn'] }}"
    ecs_volumetype: "{{ vm_vars['ecs_volumetype'] }}"
    ecs_ram: "{{ vm_vars['ecs_ram'] }}"
    ecs_vcpus: "{{ vm_vars['ecs_vcpus'] }}"
    ecs_adminkey: "{{ vm_vars['ecs_adminkey'] }}"
    keypair_file: "{{ vm_vars['keypair_file'] }}"

    # EVS variables
    evs_availability_zone: "{{ evs_vars['evs_availability_zone'] }}"
    evs_volume_type: "{{ evs_vars['evs_volume_type'] }}"
    evs_size: "{{ evs_vars['evs_size'] }}"
    
    # ELB variables
    admin_state_up: "{{ elb_vars['admin_state_up'] }}"
    elb_availability_zone: "{{ elb_vars['elb_availability_zone'] }}"
    elb_bandwidth: "{{ elb_vars['elb_bandwidth'] }}"
    elb_type: "{{ elb_vars['elb_type'] }}"
    elb_secgroup_name: "{{ elb_vars['elb_secgroup_name'] }}"
    
    # Listener-specific variables
    listener_protocol: "{{ elb_listener_vars['listener_protocol'] }}"
    listener_port: "{{ elb_listener_vars['listener_port'] }}"
    listener_backend_protocol: "{{ elb_listener_vars['listener_backend_protocol'] }}"
    listener_lb_algorithm: "{{ elb_listener_vars['listener_lb_algorithm'] }}"
    
    # DNS variables
    zone_description: "{{ dns_vars['zone_description'] }}"
    zone_email: "{{ dns_vars['zone_email'] }}"
    zone_ttl: "{{ dns_vars['zone_ttl'] }}"

    # RDS variables
    rds_availability_zone: "{{ rds_vars['rds_availability_zone'] }}"
    rds_vpc_name: "{{ rds_vars['rds_vpc_name'] }}"
    rds_type: "{{ rds_vars['rds_type'] }}"
    rds_version: "{{ rds_vars['rds_version'] }}"
    rds_root_password: "{{ rds_vars['rds_root_password'] }}"
    rds_port: "{{ rds_vars['rds_port'] }}"
    rds_ram: "{{ rds_vars['rds_ram'] }}"
    rds_volume_size: "{{ rds_vars['rds_volume_size'] }}"
    
    # Action variables
    localaction: "create"

  roles:
    - role: "otc_auth"
    - role: "otc_vpc"
    - role: "otc_subnet"
    - role: "otc_secgroup"
    - role: "otc_keypair"
    - role: "otc_eip"
    - role: "otc_ecs"
    - role: "otc_dns"
      vars:
        localaction: "ptrcreate"
    - role: "otc_vpc"
      vars:
        localaction: "router"
    - role: "otc_dns"
      vars:
        localaction: "create"
